#!/bin/sh
RED="\033[1;31m"
GREEN="\033[1;32m"
COLOR_RESET="\033[0m"

linter_exit_code=1
staged_files=$(git diff --cached --diff-filter=d --name-only | grep -E '.js$|.vue$') # grab only .js or .vue files

./node_modules/.bin/eslint $staged_files --fix
linter_exit_code=$?

git add -f $staged_files

if [ $linter_exit_code -ne 0 ]
then
  echo "${RED} ❌ Linter errors have occurred :(${COLOR_RESET}"
  exit 1
else
  echo "${GREEN} ✔ ESlint did not find any errors :)${COLOR_RESET}"
  exit 0
fi