version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  commit-message:
    prefix: "⬆️"
  pull-request-branch-name:
    separator: "-"
  reviewers:
    - "adyen/team-lume"