version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/packages/*'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: '⬆️ '
    ignore:
      - dependency-name: 'vue'
      - dependency-name: 'd3'
