version: '3.9'
services:
  web:
    container_name: lume
    tty: true
    stdin_open: true
    entrypoint: ['bash']
    build:
      context: .
      args:
        docker_image: $DOCKER_IMAGE
    ports:
      - '9002:9002' # Vue 2 Storybook
      - '9003:9003' # Vue 3 Storybook
    volumes:
      - ./:/home/node/lume
