name: 🚀 Feature request
description: Propose a new feature to be added to Lume
labels: [feature request, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the project and taking the time to fill out this feature request!
  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: problem-motivation
    attributes:
      label: Problem/motivation
      description: Please provide valid reason(s) why this should be added to Lume.
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Describe alternatives you've considered
      description: What alternative solutions or features have you considered before making this request?
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: What resources (links, screenshots, etc.) do you have to assist this effort?
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://github.com/Adyen/lume/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label: Read the [Contributing Guidelines](https://github.com/Adyen/lume/blob/main/CONTRIBUTING.md).
          required: true
        - label: Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
          required: true
