name: Publish both Lume packages

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: release

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Use Node version from .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

      - name: Install dependencies
        run: npm install

      - name: Build the package
        run: npm run build

      - name: Publish Vue 2 package to npm registry
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_ADYEN_LUME_TOKEN }}
          npm publish --access=restricted --workspace=packages/vue2

      - name: Publish Vue 3 package to npm registry
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_ADYEN_LUME_VUE3_TOKEN }}
          npm publish --access=restricted --workspace=packages/vue3
